CALL .\arch-scripts-dir.bat
CALL .\cp-dotnet-util-cfg-files.bat
CALL .\cp-mk-fs-dirs-pair-cfg.bat
CALL .\cp-dotnet-bkp-bins.bat
CALL .\cp-dotnet-util-bins.bat
CALL .\arch-dotnet-util-cfg-files.bat
CALL .\arch-dotnet-util-cfg-dirs.bat
CALL .\arch-ignored-src-files.bat
CALL .\arch-dotnet-util-dirs.bat
