export enum CmdCommand {
  Help = 1,
  ListNotes,
  CreateNoteBook,
  CreateNoteBookInternal,
  CreateNote,
  CreateNoteInternal,
  CopyNotes,
  DeleteNotes,
  MoveNotes,
  RenameNote,
  UpdateNote,
  ReorderNotes,
  NormalizeNote,
  NormalizeNoteIdxes,
  NormalizeNotesHcy,
}

export enum TrmrkStorageOption {
  IndexedDB,
  FileSystemApi,
  MsGraphApi,
  GoogleApi,
  DropBoxApi,
  LocalFilesTrmrkRestApi,
  WinOSLocalFilesTrmrkRestApi,
  MsGraphTrmrkRestApi,
  GoogleTrmrkRestApi,
  DropBoxTrmrkRestApi,
}
