export const tailwindClassesCore = [
  "absolute",
  "bottom-0",
  "border-[1px]",
  "border-[2px]",
  "content-center",
  "flex-col",
  "justify-end",
  "justify-self-center",
  "h-full",
  "overflow-hidden",
  "min-h-full",
  "max-h-full",
  "ml-[2px]",
  "mr-[2px]",
  "relative",
  "right-[-25px]",
];
